AWSTemplateFormatVersion: 2010-09-09
Description: >
  Creates a complete AWS Stack for the Solace Bus Demo including: Map UI,
  Backend Geo Services, AWS Elastic Search domain with a fully configured
  instance of Kibana.
Metadata:
  'AWS::CloudFormation::Designer':
    c55898ea-8649-463f-89dd-54a2a7de52f0:
      size:
        width: 60
        height: 60
      position:
        x: 510
        'y': 120
      z: 0
      embeds: []
    372ea895-df4f-4ca2-b669-c515338caa1e:
      size:
        width: 60
        height: 60
      position:
        x: 340
        'y': 120
      z: 0
      dependson:
        - c55898ea-8649-463f-89dd-54a2a7de52f0
    607bd178-feba-4bad-a5ff-7213ceb1fdd2:
      source:
        id: 372ea895-df4f-4ca2-b669-c515338caa1e
      target:
        id: c55898ea-8649-463f-89dd-54a2a7de52f0
      z: 1
Parameters:
  Owner:
    Type: String
    Description: >-
      Username, in lowercase, of the person who owns this instance (e.g.
      ushukla). Max 7 characters.
    Default: none
    AllowedPattern: '^[a-z]+$'
    MaxLength: 7
    ConstraintDescription: Username cannot exceed 7 characters.
  Purpose:
    Type: String
    Description: >-
      Purpose of this stack. Should include the event/engagement/session it is
      intended for, if any.
    Default: ''
    MinLength: 0
    MaxLength: 100
  EndDate:
    Type: String
    Description: Expiry date of this instance (mmddyyyy).
    Default: 12312020
    AllowedPattern: '^[0-9]{2}[0-9]{2}[0-9]{4}$'
    ConstraintDescription: Please enter a date in the format mmddyyyy.
Resources:
  SolaceBusDemoESDomain:
    Type: 'AWS::Elasticsearch::Domain'
    Properties:
      AccessPolicies:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                - !Sub 'arn:aws:iam::${AWS::AccountId}:root'
            Action: 'es:*'
            Resource: !Sub >-
              arn:aws:es:${AWS::Region}:${AWS::AccountId}:domain/${AWS::StackName}/*
      ElasticsearchVersion: '7.1'
      ElasticsearchClusterConfig:
        InstanceType: t2.small.elasticsearch
        InstanceCount: 1
        DedicatedMasterEnabled: true
        DedicatedMasterType: t2.small.elasticsearch
        DedicatedMasterCount: 3
      EBSOptions:
        EBSEnabled: true
        VolumeType: gp2
        VolumeSize: 10
      Tags:
        - Key: Owner
          Value: !Ref Owner
        - Key: Purpose
          Value: !Ref Purpose
        - Key: EndDate
          Value: !Ref EndDate
        - Key: Notice
          Value: Created by Solace Bus Demo CloudFormation Template
    Metadata:
      'AWS::CloudFormation::Designer':
        id: c55898ea-8649-463f-89dd-54a2a7de52f0
  KibanaConfigLambda:
    Type: 'AWS::Lambda::Function'
    Properties:
      Runtime: python3.8
      Handler: lambda_function.lambda_handler
      Description: Invoked to configure Kibana once Elastic Search setup is complete.
      Code:
        S3Bucket: bus-demo-resources
        S3Key: bus-demo-kibana-config-lambda.zip
      Environment:
        Variables:
          BUS_DEMO_S3_BUCKET: bus-demo-resources
          KIBANA_CONFIG_S3_OBJECT_KEY: bus-demo-kibana-object-export.json
          KIBANA_ENDPOINT: !Join [ '',[!GetAtt SolaceBusDemoESDomain.DomainEndpoint,/_plugin/kibana/api/saved_objects/_bulk_create]]
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 372ea895-df4f-4ca2-b669-c515338caa1e
    DependsOn:
      - SolaceBusDemoESDomain